// <auto-generated />
using BasicForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicForumApp.Data.Migrations
{
    [DbContext(typeof(BasicForumAppDbContext))]
    [Migration("20221006083727_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BasicForumApp.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Nqkvo Pisanie za purviq post mnogo e tupo.",
                            Title = "Nqkvo Zaglavie"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Nqkvo Pisanie za vtoriq post mnogo e tupo.",
                            Title = "Nqkvo Vtoro Zaglavie"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Nqkvo Pisanie za tretiq post mnogo e tupo.",
                            Title = "Nqkvo Treto Zaglavie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
